### ISSUE TITLE
Android app crashing on v2.0.6

### ISSUE THREAD

**Issue by hrithvik123** [eduardoRoth/media-player#9]
The android app is crashing on startup. Here's the error:

``
2025-01-06 01:18:02.537  5908-5908  AndroidRuntime          app.iptvweb                          E  FATAL EXCEPTION: main
                                                                                                    Process: app.iptvweb, PID: 5908
                                                                                                    java.lang.RuntimeException: Unable to get provider androidx.startup.InitializationProvider: androidx.startup.StartupException: java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/lifecycle/ReportFragment$ActivityInitializationListener;
                                                                                                    	at android.app.ActivityThread.installProvider(ActivityThread.java:8489)
                                                                                                    	at android.app.ActivityThread.installContentProviders(ActivityThread.java:7989)
                                                                                                    	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7675)
                                                                                                    	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2478)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:230)
                                                                                                    	at android.os.Looper.loop(Looper.java:319)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8919)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
                                                                                                    Caused by: androidx.startup.StartupException: java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/lifecycle/ReportFragment$ActivityInitializationListener;
                                                                                                    	at androidx.startup.AppInitializer.doInitialize(AppInitializer.java:187)
                                                                                                    	at androidx.startup.AppInitializer.discoverAndInitialize(AppInitializer.java:238)
                                                                                                    	at androidx.startup.AppInitializer.discoverAndInitialize(AppInitializer.java:206)
                                                                                                    	at androidx.startup.InitializationProvider.onCreate(InitializationProvider.java:45)
                                                                                                    	at android.content.ContentProvider.attachInfo(ContentProvider.java:2700)
                                                                                                    	at android.content.ContentProvider.attachInfo(ContentProvider.java:2670)
                                                                                                    	at android.app.ActivityThread.installProvider(ActivityThread.java:8484)
                                                                                                    	at android.app.ActivityThread.installContentProviders(ActivityThread.java:7989) 
                                                                                                    	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7675) 
                                                                                                    	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0) 
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2478) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:230) 
                                                                                                    	at android.os.Looper.loop(Looper.java:319) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8919) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103) 
                                                                                                    Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/lifecycle/ReportFragment$ActivityInitializationListener;
                                                                                                    	at androidx.lifecycle.ProcessLifecycleInitializer.create(ProcessLifecycleInitializer.kt:37)
                                                                                                    	at androidx.lifecycle.ProcessLifecycleInitializer.create(ProcessLifecycleInitializer.kt:25)
                                                                                                    	at androidx.startup.AppInitializer.doInitialize(AppInitializer.java:180)
                                                                                                    	at androidx.startup.AppInitializer.discoverAndInitialize(AppInitializer.java:238) 
                                                                                                    	at androidx.startup.AppInitializer.discoverAndInitialize(AppInitializer.java:206) 
                                                                                                    	at androidx.startup.InitializationProvider.onCreate(InitializationProvider.java:45) 
                                                                                                    	at android.content.ContentProvider.attachInfo(ContentProvider.java:2700) 
                                                                                                    	at android.content.ContentProvider.attachInfo(ContentProvider.java:2670) 
                                                                                                    	at android.app.ActivityThread.installProvider(ActivityThread.java:8484) 
                                                                                                    	at android.app.ActivityThread.installContentProviders(ActivityThread.java:7989) 
                                                                                                    	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7675) 
                                                                                                    	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0) 
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2478) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:230) 
                                                                                                    	at android.os.Looper.loop(Looper.java:319) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8919) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103) 
                                                                                                    Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.lifecycle.ReportFragment$ActivityInitializationListener" on path: DexPathList[[zip file "/data/app/~~EOZUyVOaBDET_cblOWhm6A==/app.iptvweb-7QR_RNLAYRF4YZ1D3CMycg==/base.apk"],nativeLibraryDirectories=[/data/app/~~EOZUyVOaBDET_cblOWhm6A==/app.iptvweb-7QR_RNLAYRF4YZ1D3CMycg==/lib/arm64, /system/lib64, /system_ext/lib64]]
                                                                                                    	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
                                                                                                    	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
                                                                                                    	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                                                    	at androidx.lifecycle.ProcessLifecycleInitializer.create(ProcessLifecycleInitializer.kt:37) 
                                                                                                    	at androidx.lifecycle.ProcessLifecycleInitializer.create(ProcessLifecycleInitializer.kt:25) 
                                                                                                    	at androidx.startup.AppInitializer.doInitialize(AppInitializer.java:180) 
                                                                                                    	at androidx.startup.AppInitializer.discoverAndInitialize(AppInitializer.java:238) 
                                                                                                    	at androidx.startup.AppInitializer.discoverAndInitialize(AppInitializer.java:206) 
                                                                                                    	at androidx.startup.InitializationProvider.onCreate(InitializationProvider.java:45) 
                                                                                                    	at android.content.ContentProvider.attachInfo(ContentProvider.java:2700) 
                                                                                                    	at android.content.ContentProvider.attachInfo(ContentProvider.java:2670) 
                                                                                                    	at android.app.ActivityThread.installProvider(ActivityThread.java:8484) 
                                                                                                    	at android.app.ActivityThread.installContentProviders(ActivityThread.java:7989) 
                                                                                                    	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7675) 
                                                                                                    	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0) 
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2478) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:230) 
                                                                                                    	at android.os.Looper.loop(Looper.java:319) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8919) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
 ``

The code I am using is:

```
import { MediaPlayer } from "@eduardoroth/media-player";
import { useAuth } from "@providers/AuthProvider";
import { CategoryType } from "@types/index";
import { adMob } from "@utils/capacitorAdMob";
import { forwardRef, useEffect, useImperativeHandle } from "react";

interface NativePlayerProps {
  stream: string | null;
  poster: string;
  type: CategoryType;
  onFinished?: () => Promise<void>;
  onProgress?: (time: number) => Promise<void>;
}

const NativePlayer = forwardRef(
  (
    { stream, poster, type, onFinished, onProgress }: NativePlayerProps,
    ref
  ) => {
    const playerId = "video-player";
    const disposePlayer = () => {
      MediaPlayer.removeAllListeners({ playerId });
      MediaPlayer.removeAll();
    };

    const { isUserPro } = useAuth();

    const initializeNativePlayer = async (seektime?: number) => {
      if (stream) {
        try {
          await MediaPlayer.create({
            url: stream,
            playerId,
            android: {
              enablePiP: true,
              enableBackgroundPlay: true,
              openInFullscreen: true,
              automaticallyEnterPiP: true,
            },
          });

          MediaPlayer.addListener(
            "MediaPlayer:Ready",
            async (_event: { playerId: string }) => {
              if (seektime !== undefined) {
                await MediaPlayer.setCurrentTime({ playerId, time: seektime });
              }

              await MediaPlayer.play({ playerId });
            }
          );

          MediaPlayer.addListener(
            "MediaPlayer:TimeUpdated",
            async (event: { playerId: string; currentTime: number }) => {
              if (event.currentTime && onProgress) {
                await onProgress(event.currentTime);
              }
            }
          );

          MediaPlayer.addListener(
            "MediaPlayer:Ended",
            async (_event: { playerId: string }) => {
              if (onFinished) await onFinished();
            }
          );

          MediaPlayer.addListener(
            "MediaPlayer:Removed",
            async (_event: { playerId: string }) => {
              if (!isUserPro) {
                adMob.interstitial();
              }
            }
          );
        } catch (error) {
          console.error("Error initializing native player:", error);
        }
      }
    };

    useEffect(() => {
      return () => {
        disposePlayer();
      };
    }, [stream, type]);

    useImperativeHandle(ref, () => ({
      initializeNativePlayer,
    }));

    return (
      <>
        <div id="video-player" slot="fixed"></div>
      </>
    );
  }
);
export default NativePlayer;
```

Thanks for the great work.

**Comment by eduardoRoth** [comment]
@hrithvik123 can you try doing a `Clean project` and `Make project` again?

**Comment by hrithvik123** [comment]
@eduardoRoth I did. Still the same issue.

**Comment by fabriciovasc** [comment]
i have the same problem

**Comment by hrithvik123** [comment]
@eduardoRoth I upgraded to v3.1.0 and the issue still persists. Could you help with this?

**Comment by eduardoRoth** [comment]
Will take a look this week. Can you give me more detail about the device you're using?

**Comment by fabriciovasc** [comment]
@eduardoRoth 

> ionic info

```
Ionic:

   Ionic CLI                     : 7.2.0 (C:\ProgramData\nvm\v22.8.0\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 8.4.1
   @angular-devkit/build-angular : 19.0.7
   @angular-devkit/schematics    : 19.0.7
   @angular/cli                  : 19.0.7
   @ionic/angular-toolkit        : 12.1.1

Capacitor:

   Capacitor CLI      : 6.2.0
   @capacitor/android : 6.2.0
   @capacitor/core    : 6.2.0
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 2.0.1

System:

   NodeJS : v22.8.0 (C:\Program Files\nodejs\node.exe)
   npm    : 10.8.2
   OS     : Windows 10
```

> Emulator

I also tested it on a real device

```
Properties
avd.ini.displayname      Pixel_3a_API_34_extension_level_7_x86_64
avd.ini.encoding         UTF-8
AvdId                    Pixel_3a_API_34_extension_level_7_x86_64
disk.dataPartition.size  6442450944
hw.accelerometer         yes
hw.arc                   false
hw.audioInput            yes
hw.battery               yes
hw.camera.back           emulated
hw.camera.front          emulated
hw.cpu.ncore             12
hw.device.hash2          MD5:0e6953ebf01bdc6b33a2f54746629c50
hw.device.manufacturer   Google
hw.device.name           pixel_3a
hw.dPad                  no
hw.gps                   yes
hw.gpu.enabled           yes
hw.gpu.mode              auto
hw.keyboard              yes
hw.lcd.density           440
hw.lcd.height            2220
hw.lcd.width             1080
hw.mainKeys              no
hw.ramSize               1536
hw.sdCard                yes
hw.sensors.orientation   yes
hw.sensors.proximity     yes
hw.trackBall             no
image.androidVersion.api 34
image.sysdir.1           system-images\android-34\google_apis\x86_64\
PlayStore.enabled        false
runtime.network.latency  none
runtime.network.speed    full
snapshot.present         no
tag.display              Google APIs
tag.id                   google_apis
vm.heapSize              256
```

Does this help you?

**Comment by WardPearce** [comment]
Yea running into the same issue on
https://github.com/Materialious/Materialious

**Comment by eduardoRoth** [comment]
@hrithvik123 @fabriciovasc @WardPearce this issue is fixed in version v3.1.4

You also need to be on Gradle version 8.7, so update your `gradle-wrapper.properties` file to have the value of `distributionUrl` like this:

`distributionUrl=https\://services.gradle.org/distributions/gradle-8.7-bin.zip`

**Comment by hrithvik123** [comment]
Hi @eduardoRoth 

I tried running it on v3.1.7 and still get the same error. I already tried cleaning and making the project again.

**Comment by eduardoRoth** [comment]
Plugin latest version is v3.1.4; project graddle wrapper version should be 8.7

**Comment by hrithvik123** [comment]
Sorry I meant v3.1.4, it was a typo. I did upgrade the gradle version in gradle-wrapper.properties

**Comment by eduardoRoth** [comment]
@hrithvik123 are you still getting the same error? What Ionic and Capacitor version do you have?

**Comment by hrithvik123** [comment]
Hey, I was getting the same error. I am on capacitor 6. Don't have ionic in my package.json.

**Comment by eduardoRoth** [comment]
@hrithvik123 for Capacitor v6 you should use the latest version of `v3`
Can you retest?

**Comment by hrithvik123** [comment]
@eduardoRoth I upgraded to Capacitor 7 and tried with version 4.0.9 of the plugin. It works. Thank you :)
